###
GET http://localhost:5174/api/tia-muniki

###
POST http://localhost:5174/api/tia-muniki
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkhlbnJ5IEJhc3RvcyIsImlhdCI6MTUxNjIzOTAyMn0.nKa3TfeXgMKXDV7UXrvjnRhowtV2svKGnAD-14erJDc
Content-Type: application/json

{
   "name": "Monequipe",
   "job": "everything"
}